---
#archtest
#root@redeye
#root@10.10.4.179
#root@10.10.4.184
all:
  hosts:
    #    geosword:
    #      ansible_host: root@10.10.4.100
    #redeye:
    #  ansible_host: root@10.10.4.101
    hoff:
      ansible_host: root@10.10.4.123
    #milano:
    #  ansible_host: root@10.100.38.120
    #vbox:
    #  ansible_host: root@10.10.4.122
