---
# this MUST be run as root, so that it can create the non priviledged user.
- hosts: all
  gather_facts: false
  tasks:
    - name: "check for python"
      raw: test -e /usr/bin/python2
      changed_when: false
      ignore_errors: true
      register: pythoninstalled

    - name: install python if its not there.
      raw: pacman -S --noconfirm python2
      when:
        - pythoninstalled.rc != 0

- hosts: all
  tasks:
# update the mirrors list
    - name: download pacman mirror list
      get_url:
        url: "https://www.archlinux.org/mirrorlist/?country=US&country=GB&protocol=http&ip_version=4&use_mirror_status=on"
        dest: "/etc/pacman.d/mirrorlist"

    - name: "uncomment `#Server` in pacman mirror list"
      replace:
        dest: "/etc/pacman.d/mirrorlist"
        regexp: '^#Server'
        replace: 'Server'

    - name: "uncomment colors"
      lineinfile:
        dest: /etc/pacman.conf
        state: "present"
        regexp: "^Color"
        insertafter: "^#Color"
        line: "Color"

# install a bunch of stuff
    - name: install a bunch of stuff
      package:
        name: "{{ item }}"
        state: present
      with_items:
# basic stuff
        - base-devel
        - breeze-gtk
        - bind-tools
        - dolphin
        - evolution
        - evolution-ews
        - dhcpcd
        - git
        - hwinfo
        - ipcalc
        - keychain
        - keychain
        - keepassxc
        - konsole
        - kde-gtk-config
        - net-tools
        - nvidia
        - nvidia-settings
        - nvidia-utils
        - pavucontrol
        - plasma
        - pwgen
        - rdesktop
        - riot-desktop
        - sddm
        - sudo
        - syncthing
        - tmux
        - vim
        - wmctrl
        - xdotool
        - xorg
        - xorg-xinit
# fakeroot is needed for makepkg which is needed to install google-chrome.
        - fakeroot
# extra things that arent required for a "functioning" system
        - kcalc
        - syncthing
# THERES more STUFF TO DO FOR SETTING UP BLUETOOTH. check the archlinux bluetooth page for details
        - bluez
        - bluez-utils
      tags: packages

# Allow members of wheel to privilege escalate without a password
    - name: allow wheel passwordless sudo privs.
      replace:
        dest: "/etc/sudoers"
        regexp: "^# %wheel ALL=\\(ALL\\) NOPASSWD"
        replace: "%wheel ALL=(ALL) NOPASSWD"

## create the group for the non privileged user
    - name: create group
      group:
        name: dylanh
      tags:
        - createuser

## create my non privileged user
    - name: create user
      user:
        name: dylanh
        shell: /bin/bash
# lp group allows bluetooth access, wheel allows root access to things
        groups: wheel,dylanh,lp
        home: /home/dylanh
      tags:
        - createuser

    - name: create the .ssh folder
      file:
        path: /home/dylanh/.ssh
        mode: '0700'
        state: directory
        owner: dylanh
        group: dylanh
      tags:
        - createuser
#
 
## configuration
    - name: get an xorg configuration using nvidia-xconfig
      command: /usr/bin/nvidia-xconfig
      args:
        creates: /etc/X11/xorg.conf

# this means we can use the nvidia-settings kde app to configure the displays, and save the configuration
# in the app without it complaining about permissions.
 
    - name: make the xorg configuration editable by uses in the wheel group (me)
      file:
        path: /etc/X11
        group: wheel
        mode: '0775'

    - name: make the file created by nvidia-xconfig writable by wheel
      file:
        path: /etc/X11/xorg.conf
        group: wheel
        mode: '0775'

    - name: xinitrc
      copy:
        dest: /home/dylanh/.xinitrc
        content: |
          exec startkde
        owner: dylanh
        group: dylanh

    - name: create an sddm config drop in folder
      file: 
        path: /etc/sddm.conf.d/
        state: directory
        mode: '0755'

    - name: create the sddm theme drop in
      copy:
        dest: /etc/sddm.conf.d/theme.conf
        content: |
          [Theme]
          Current=breeze
          CursorTheme=
          DisableAvatarsThreshold=7
          EnableAvatars=true
          FacesDir=/usr/share/sddm/faces
          ThemeDir=/usr/share/sddm/themes

# this just checks out the repo, you still need to cd to it and run makepkg -s
    - name: clone google-chrome repo
      git:
        repo: https://aur.archlinux.org/google-chrome.git
        dest: /usr/src/google-chrome
        update: no

    - name: make google-chrome source code available to me
      file: 
        path: /usr/src/google-chrome
        group: wheel
        mode: '0775'

    - name: run makepkg in the google-chrome folder we just made
      command: chdir=/usr/src/google-chrome makepkg -s --noconfirm
      args:
        creates: /usr/src/google-chrome/google-chrome-*.pkg.tar.xz
      become: true
      become_user: dylanh

# This pattern could be a bit loose
    - name: get a list of pkg.tar.xz files to install
      find:
        paths: /usr/src/google-chrome/
        patterns: '*.pkg.tar.xz'
      register: chromepackage

# now to install it, provided it not installed.
    - name: debug
      debug:
        msg: "file to install is {{ chromepackage.files }}"

    - name: now install the package we just makepkg'd. I hope we can install using wildcards.
      command: chdir=/usr/src/google-chrome pacman -U --noconfirm {{ item.path | basename }}
      with_items: "{{ chromepackage.files }}"
      failed_when: chromepackage.matched == 0
      args:
        creates: /usr/bin/google-chrome-stable
      when:
        - chromepackage.matched > 0


# Install sublime text
    - name: fetch sublime repo key for arch
      get_url: 
        url: https://download.sublimetext.com/sublimehq-pub.gpg
        dest: /var/tmp/sublimehq-pub.gpg
    - name: add the key
      command: pacman-key --add /var/tmp/sublimehq-pub.gpg
    - name: sign it
      command: pacman-key --lsign-key 8A8F901A
    - name: remove the key from /var/tmp
      file:
        path: /var/tmp/sublimehq-pub.gpg
        state: absent
   # add the sublime repo to pacman.conf
    - name: add sublime repo to pacman.conf
      blockinfile:
        path: /etc/pacman.conf
        block: |
          [sublime-text]
          Server = https://download.sublimetext.com/arch/dev/x86_64

    - name: now install. We'll use command cause we need special pacman flags (-uy) This could take a while, check /var/log/pacman.log for progress
      command: pacman -Syu --noconfirm sublime-text
      args:
        creates: /opt/sublime_text/sublime_text

# bash configuration
    - name: install bash_profile
      copy:
        dest: /home/dylanh/.bash_profile
        mode: '0644'
        content: |
          if [ -f ~/.bashrc ]; then
          	. ~/.bashrc
          fi

    - name: install bashrc
      copy:
        dest: /home/dylanh/.bashrc
        src: files/bash/bashrc
        owner: dylanh
        mode: '0644'

# we going to use systemd-resolved against my better judgement
    - name: replace /etc/resolv.conf with a link to system-resolved configuration
      file: 
        src: /run/systemd/resolve/stub-resolv.conf
        dest: /etc/resolv.conf
        state: link
        force: yes

    - name: set the keyboard layout to UK
      copy:
        dest: /etc/vconsole.conf
        content: 'KEYMAP=uk'

    - name: set the timezone
      timezone:
        name: Europe/London

    - name: set the locale
      locale_gen:
        name: en_GB.UTF-8
        state: present

    - name: create some helpful folders
      file:
        path: "/home/dylanh/{{ item }}"
        state: directory
        mode: "0755"
        group: "dylanh"
        owner: "dylanh"
      become: true
      become_user: dylanh
      with_items: ["development"]
      tags:
        - createfolders

# Some stuff for when we are testing with vagrant
   - name: Include virtualbox operations if we are in virtualbox
     include: virtualbox.yaml
     when: 
        - ansible_virtualization_type == 'virtualbox'

# For setting KDE shortcut keys and custom shortcuts, copy the following files: (~/.config)
# kglobalshortcutsrc - global shortcuts
# khotkeysrc - custom shortcuts
# plasma-org.kde.plasma.desktop-appletsrc - If you have hidden system tray applets. This may not exist until you actually try to override some of them
