---
# this must be run as root, so that it can create the non priviledged user.

- name: Setup Dylans Workstation
  hosts: all
  tasks:
## create my non privileged user
    - name: create user
      user:
        name: dylanh
        shell: /bin/bash
        groups: wheel,dylanh
        home: /home/dylanh
## install a bunch of stuff
#    - name: install a bunch of stuff
#      package:
#        name: "{{ item }}"
#        state: present
#      with_items:
#        - 

    - name: Install nvidia-settings
      package:
        name: nvidia-settings
        state: present

    - name: Install nvidia-utils
      package:
        name: nvidia-utils
        state: present
 
## install packages
    - name: Install xorg
      package:
        name: xorg
        state: present

    - name: Install xorg-xinit
      package:
        name: xorg
        state: present

    - name: Install plasma
      package:
        name: plasma
        state: present

    - name: Install sddm
      package:
        name: sddm
        state: present

    - name: Install konsole
      package:
        name: konsole
        state: present

    - name: Install dolphin
      package:
        name: dolphin
        state: present

    - name: Install git
      package:
        name: git
        state: present

    - name: Install vim
      package:
        name: vim
        state: present

    - name: Install kcalc
      package:
        name: kcalc
        state: present

    - name: Install syncthing
      package:
        name: syncthing
        state: present

    - name: Install breeze-gtk
      package:
        name: breeze-gtk
        state: present

## configuration

    - name: xinitrc
      copy:
        dest: /home/dylanh/.xinitrc
        content: |
          exec startkde

    - name: create an sddm config drop in folder
      file: 
        path: /etc/sddm.conf.d/

    - name: create the sddm theme drop in
      copy:
        dest: /etc/sddm.conf.d/theme.conf
        content: |
          [Theme]
          Current=breeze
          CursorTheme=
          DisableAvatarsThreshold=7
          EnableAvatars=true
          FacesDir=/usr/share/sddm/faces
          ThemeDir=/usr/share/sddm/themes

# fakeroot is needed for makepkg which is needed to install google-chrome.
    - name: Install fakeroot
      package:
        name: fakeroot
        state: present

# this just checks out the repo, you still need to cd to it and run makepkg -s
    - name: clone google-chrome repo
      git:
        repo: https://aur.archlinux.org/google-chrome.git
        dest: /usr/src/google-chrome
        update: no
    - name: make google-chrome source code available to me
      file: 
        path: /usr/src/google-chrome
        group: wheel
        mode: '0775'

# TODO if its arch, use https://www.archlinux.org/mirrorlist/?country=US & https://www.archlinux.org/mirrorlist/?country=GB to randomly select some mirrors and create /etc/pacman.d/mirrorlist The reason for a mixture is because in some cases the mirrors dont have all the files needed for some packages (you saw this with dolphin)
