---
# this must be run as root, so that it can create the non priviledged user.

- name: Setup Dylans Workstation
  hosts: all
  tasks:
## create my non privileged user
    - name: create user
      user:
        name: dylanh
        shell: /bin/bash
        groups: wheel,dylanh
        home: /home/dylanh
# install a bunch of stuff
    - name: install a bunch of stuff
      package:
        name: "{{ item }}"
        state: present
      with_items:
# basic stuff
        - nvidia
        - nvidia-settings
        - nvidia-utils
        - xorg
        - xorg-xinit
        - plasma
        - sddm
        - konsole
        - dolphin
        - git
        - vim
        - breeze-gtk
        - kde-gtk-config
# fakeroot is needed for makepkg which is needed to install google-chrome.
        - fakeroot
# extra things that arent required for a "functioning" system
        - kcalc
        - syncthing
# THERES more STUFF TO DO FOR SETTING UP BLUETOOTH. check the archlinux bluetooth page for details
        - bluez
        - bluez-utils

 
## configuration
    - name: get an xorg configuration using nvidia-xconfig
      command: /usr/bin/nvidia-xconfig
      args:
        creates: /etc/X11/xorg.conf

# this means we can use the nvidia-settings kde app to configure the displays, and save the configuration
# in the app without it complaining about permissions.
 
    - name: make the xorg configuration editable by uses in the wheel group (me)
      file:
        path: /etc/X11
        group: wheel
        mode: '0775'

    - name: make the file created by nvidia-xconfig writable by wheel
      file:
        path: /etc/X11/xorg.conf
        group: wheel
        mode: '0775'

    - name: xinitrc
      copy:
        dest: /home/dylanh/.xinitrc
        content: |
          exec startkde

    - name: create an sddm config drop in folder
      file: 
        path: /etc/sddm.conf.d/

    - name: create the sddm theme drop in
      copy:
        dest: /etc/sddm.conf.d/theme.conf
        content: |
          [Theme]
          Current=breeze
          CursorTheme=
          DisableAvatarsThreshold=7
          EnableAvatars=true
          FacesDir=/usr/share/sddm/faces
          ThemeDir=/usr/share/sddm/themes

# this just checks out the repo, you still need to cd to it and run makepkg -s
    - name: clone google-chrome repo
      git:
        repo: https://aur.archlinux.org/google-chrome.git
        dest: /usr/src/google-chrome
        update: no
    - name: make google-chrome source code available to me
      file: 
        path: /usr/src/google-chrome
        group: wheel
        mode: '0775'
    - name: run makepkg in the google-chrome folder we just made
      command: chdir=/usr/src/google-chrome makepkg -s --noconfirm
      args:
        creates: /usr/src/google-chrome/google-chrome-*.pkg.tar.xz

# TODO if its arch, use https://www.archlinux.org/mirrorlist/?country=US & https://www.archlinux.org/mirrorlist/?country=GB to randomly select some mirrors and create /etc/pacman.d/mirrorlist The reason for a mixture is because in some cases the mirrors dont have all the files needed for some packages (you saw this with dolphin)
