# this MUST be run as root, so that it can create the non priviledged user.
# VARS - take network config so we can specify things like search domain.

- hosts: all
  gather_facts: false
  tasks:
    - name: "check for python"
      raw: test -e /usr/bin/python2
      changed_when: false
      ignore_errors: true
      register: pythoninstalled

# TODO check the date on /var/lib/pacman/sync/core.db, if its today, skip the synchronisation
    - name: Synchronise the package databases
      raw : /usr/bin/pacman -Syy

    - name: install python if its not there.
      raw: /usr/bin/pacman -S --noconfirm python2
      when:
        - pythoninstalled.rc != 0

- hosts: all
  tasks:
    - name: include some global variables
      include_vars: "{{ item }}"
      with_items:
        - vars/main.yml

# update the mirrors list
    - name: download pacman mirror list
      get_url:
        url: "https://www.archlinux.org/mirrorlist/?country=GB&country=DE&country=US&protocol=http&protocol=https&ip_version=4&use_mirror_status=on"
        dest: "/etc/pacman.d/mirrorlist"
        force: yes
      tags: packages

    - name: "uncomment `#Server` in pacman mirror list"
      replace:
        dest: "/etc/pacman.d/mirrorlist"
        regexp: '^#Server'
        replace: 'Server'
      tags: packages

    - name: Synchronise the package databases
      command: /usr/bin/pacman -Syy
      tags: sync-packages

    - name: Refresh the pacman-keys
      command: /usr/bin/pacman-key --refresh-keys
      tags: sync-packages


    - name: "uncomment colors"
      lineinfile:
        dest: /etc/pacman.conf
        state: "present"
        regexp: "^Color"
        insertafter: "^#Color"
        line: "Color"

# install a bunch of stuff
# TODO When we want to install new packages IT MUST go here, however there is a lot of stuff in here
# That we either dont want or dont need to run at the same time, so perhaps seperate out the installation
# of packages to a different play, or put it in the wsconfig play, but only run the required tasks when a variable is 
# set e.g. installpackages=true
    - name: install a bunch of stuff
      command: "/usr/bin/pacman -S --noconfirm {{ item }}"
      with_items:
# basic stuff
        - ansible
        - aws-cli
        - base-devel
        - breeze-gtk
        - bind-tools
# THERES more STUFF TO DO FOR SETTING UP BLUETOOTH. check the archlinux bluetooth page for details
        - bluez
        - bluez-utils
        - cups
        - cronie
        - docker
        - dolphin
# fakeroot is needed for makepkg which is needed to install google-chrome.
        - fakeroot
        - firefox
# Ghostscript is needed for printing to work.
        - ghostscript
        - git
        - grub
        - gnome-keyring
        - hwinfo
        - ipcalc
        - icu
        - jq
        - kcalc
        - keychain
        - keepassxc
        - konsole
        - kde-gtk-config
        - kwalletmanager
        - latte-dock
        - neovim
        - net-tools
        - nvidia
        - nvidia-settings
        - nvidia-utils
        - pavucontrol
        - plasma
        - powerline
        - powerline-vim
        - powerline-fonts
        - pulseaudio
        - pulseaudio-bluetooth
        - pwgen
        - python2
        - python-virtualenv
        - python-virtualenvwrapper
        - python2-virtualenv
        - rdesktop
        - rdiff-backup
        - riot-desktop
        - rsync
        - sddm
        - subversion
        - sudo
        - syncthing
        - tcpdump
        - terraform
        - tmux
        - traceroute
        - vim
        - wget
        - wmctrl
        - xclip
        - xdotool
        - xorg
        - xorg-xinit
        - xsel
# zathura is a minimal pdf viewer with vim keybindings. https://wiki.archlinux.org/index.php/Zathura
        - zathura
        - zathura-pdf-mupdf
        - zsh
        - zsh-theme-powerlevel9k
      ignore_errors: true
      tags: install-packages

    - name: Disable cowsay in ansible, its just annoying
      replace:
        dest: "/etc/ansible/ansible.cfg"
        regexp: '^#nocows=1'
        replace: 'nocows=1'
      tags:
        - disablecowsay

## create the group for the non privileged user
    - name: create group
      group:
        name: dylanh
      tags:
        - createuser

# Allow members of wheel to privilege escalate without a password
    - name: allow wheel passwordless sudo privs
      replace:
        dest: "/etc/sudoers"
        regexp: "^# %wheel ALL=\\(ALL\\) NOPASSWD"
        replace: "%wheel ALL=(ALL) NOPASSWD"

## create my non privileged user
    - name: create user
      user:
        name: dylanh
        shell: /usr/bin/zsh
# lp group allows bluetooth access, wheel allows root access to things
        groups: wheel,dylanh,lp,cups
        group: dylanh
        # the password is test123
        password: "$6$8TfIqE.dd/0iUF1Q$txKOLAfCAfofs8OCljKEtXFoXJjZamLsMVe/0EVy5yvr3z2USWsrG2wRwC0c4ARWsZ4ckFPcrEcl/fp9aSn4J/"
        home: "{{ userdir }}"
      tags:
        - createuser


    - name: create the .ssh folder
      file:
        path: "{{ userdir }}/.ssh"
        mode: '0700'
        state: directory
        owner: dylanh
        group: dylanh
      tags:
        - createuser

# install kubectl. we dont use get_url here because its doing a secondary call to find out the current stable release
# for some reason using the file module to set the permissions just didnt work. It would set the directory and group, but not "other"
    - name: install kubectl
      shell:
        cmd: "curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl && chmod 775 /usr/local/sbin/kubectl"
        chdir: "/usr/local/sbin/"
        creates: "/usr/local/sbin/kubectl"
      become: yes
      tags:
        - installkubectl


    - name: enable cups for printing. This starts the socket, so if we access cups it will start it
      systemd:
        name: bluetooth.service
        state: started
        enabled: yes
      tags:
        - bluetooth

    - name: enable cups for printing. This starts the socket, so if we access cups it will start it
      systemd:
        name: org.cups.cupsd.service
        state: started
        enabled: yes
      tags:
        - cups

# Install canonical's snap from the AUR (another package management system to unify them all)
    - name: clone Snap AUR
      git:
        repo: https://aur.archlinux.org/snapd.git
        dest: /usr/src/snapd
        update: no
      tags:
        - installsnap

    - name: make snap source code available to me (dylanh user)
      file:
        path: /usr/src/snapd
        group: wheel
        mode: '0775'
      tags:
        - installsnap

    - name: Build and install snap
      command: chdir=/usr/src/snapd makepkg -sirc --noconfirm
      become: true
      become_user: dylanh
      tags:
        - installsnap

    - name: enable apparmor so that snaps dont have free reign on the system
      systemd:
        name: apparmor
        state: started
        enabled: yes
      tags:
        - installsnap

    - name: enable the snap socket. i think this listens for snap trying to connect, and starts the snapd server if so
      systemd:
        name: snapd.socket
        state: started
        enabled: yes
      tags:
        - installsnap

    - name: /snap is needed for snap client to work. A bit lame.
      file:
        src: /var/lib/snapd/snap
        dest: /snap
        state: link
      tags:
        - installsnap


    - name: enable parallel snaps (install multiple versions of the same package) We do this for helm2 and helm3
      shell:
        cmd: "/usr/bin/snap set system experimental.parallel-instances=true"
      become: yes
      tags:
        - installsnap

#  Install helm 2 from snap
    - name: install helm 2 from snap
      snap:
        name: helm
        channel: 2.16/stable
        classic: yes
      tags:
        - installhelm

    - name: link helm 2 from the snaps folder to somewhere usefull
      file:
        src: /var/lib/snapd/snap/helm/current/helm
        dest: /usr/local/sbin/helm2
        state: link
      tags:
        - installhelm


#  Install helm 3 from snap
    - name: install helm 3 from snap
      snap:
        name: helm
        classic: yes
      tags:
        - installhelm

    - name: link helm 3 from the snaps folder to somewhere usefull
      file:
        src: /var/lib/snapd/snap/helm_3/current/helm
        dest: /usr/local/sbin/helm3
        state: link
      tags:
        - installhelm

# remove the helm link from /var/lib/snapd/snap/bin/ so that we cant run helm without specifying a version.
    - name: remove snap helm link
      file:
        path: /var/lib/snapd/snap/bin/helm
        state: absent
      tags:
        - installhelm

#  Install sublime text
    - name: install sublime from snap
      snap:
        name: sublime-text
        classic: yes

# we going to use systemd-resolved against my better judgement
    - name: replace /etc/resolv.conf with a link to system-resolved configuration
      file:
        src: /run/systemd/resolve/stub-resolv.conf
        dest: /etc/resolv.conf
        state: link
        force: yes

    - name: set the keyboard layout to UK
      copy:
        dest: /etc/vconsole.conf
        content: 'KEYMAP=uk'

    - name: set the timezone
      timezone:
        name: Europe/London

    - name: set the locale
      locale_gen:
        name: en_GB.UTF-8
        state: present

    - name: make sure vfat and others are loaded at boot to prevent problems updating the kernel
      copy:
        dest: /etc/modules-load.d/vfat.conf
        content: |
          vfat
          nls_cp437
          nls_iso8859-1

# Avoid "xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)"  when using startx as user
    - name: Add the sticky bit to /usr/bin/xinit
      file:
        dest: /usr/bin/xinit
        mode: u+s
      tags:
        - stickybit


    - name: check for custom xorg config
      find:
        paths: "files/{{ inventory_hostname }}/"
        patterns: 'xorg.conf'
      register: customxorg

    - name: copy in the xorg for this host. NOTE this assumes the file is in files/hostname/xorg.conf. The file may be empty where such a file is not required.
      copy:
        src: "files/{{ inventory_hostname }}/xorg.conf"
        dest: /etc/X11/xorg.conf
        group: wheel
        mode: '0775'
      when:
        - customxorg.matched > 0

    - name: configure autoloading the nvidia modules when appropriate
      copy:
        dest: /etc/modules-load.d/nvidia.conf
        content: |
          # Load nvidia at boot
          nvidia
      when:
        - (inventory_hostname == 'milano' or inventory_hostname == 'geosword' or inventory_hostname == 'hoff')

    - name: load the nvidia modules when appropriate
      modprobe:
        name: nvidia
        state: present
      when:
        - (inventory_hostname == 'milano' or inventory_hostname == 'geosword' or inventory_hostname == 'hoff')

    - name: get an xorg configuration using nvidia-xconfig
      command: /usr/bin/nvidia-xconfig
      args:
        creates: /etc/X11/xorg.conf
      when:
        - customxorg.matched == 0
        - (inventory_hostname == 'milano' or inventory_hostname == 'geosword' or inventory_hostname == 'hoff')

    - name: make the xorg configuration editable by users in the wheel group (me)
      file:
        path: /etc/X11
        group: wheel
        mode: '0775'

    - name: xinitrc
      copy:
        dest: "{{ userdir }}/.xinitrc"
        content: |
          exec /usr/bin/startplasma-x11
        owner: dylanh
        group: dylanh

    - name: create an sddm config drop in folder
      file:
        path: /etc/sddm.conf.d/
        state: directory
        mode: '0755'
      tags:
        - sddmconfig

    - name: create the sddm theme drop in
      copy:
        dest: /etc/sddm.conf.d/theme.conf
        content: |
          [Theme]
          Current=breeze
          CursorTheme=
          DisableAvatarsThreshold=7
          EnableAvatars=true
          FacesDir=/usr/share/sddm/faces
          ThemeDir=/usr/share/sddm/themes
      tags:
        - sddmconfig

    - name: Autologin for sddm. Will be disabled later
      copy:
        dest: /etc/sddm.conf.d/autologin.conf
        content: |
          [Autologin]
          User=dylanh
          Session=plasma.desktop
      tags:
        - sddmconfig

# Some stuff for when we are testing with vagrant
    - name: Include virtualbox operations if we are in virtualbox
      include: virtualbox.yaml
      when:
        - ansible_virtualization_type == 'virtualbox'

    - name: enable & start sddm
      systemd:
        state: started
        name: sddm.service
        enabled: true

    - name: enable & start syncthing
      systemd:
        name: syncthing@dylanh.service
        state: started
        enabled: true

# Install chrome. We're not installing via snap because that is Chromium, NOT chrome
    - name: clone google-chrome repo
      git:
        repo: https://aur.archlinux.org/google-chrome.git
        dest: /usr/src/google-chrome
        update: no
      tags:
        - installchrome

    - name: make google-chrome source code available to me (dylanh user)
      file: 
        path: /usr/src/google-chrome
        group: wheel
        mode: '0775'
      tags:
        - installchrome

    - name: Build and install chrome
      command: chdir=/usr/src/google-chrome makepkg -sirc --noconfirm
      become: true
      become_user: dylanh
      tags:
        - installchrome

    - name: remove autologin config
      file:
        path: /etc/sddm.conf.d/autologin.conf
        state: absent

    - name: add the backup scripts when on geosword
      copy:
        src: "{{ item }}"
        dest: "{{ userdir }}/.tools/"
        mode: "0744"
        owner: dylanh
        group: dylanh
      with_items:
        - files/geosword/backupme.sh
        - files/geosword/backuphome.sh
      when:
        - (inventory_hostname == 'geosword')
      tags:
        - backupscripts

    - name: backup host cronjob
      cron:
        name: backup host
        minute: 0
        hour: 2
        job: "{{ userdir }}/.tools/backupme.sh"
        user: root
      when:
        - (inventory_hostname == 'geosword')
      tags:
        - backupscripts

    - name: backup home cronjob
      cron:
        name: backup home
        minute: 0
        hour: 23
        weekday: 5
        job: "{{ userdir }}/.tools/backuphome.sh"
        user: root
      when:
        - (inventory_hostname == 'geosword')
      tags:
        - backupscripts

    - name: message
      debug:
        msg: "DO THIS NOW. Set passwords for both dylanh and root to something more secure than test123!!!! ********* Do it!!!! get to tha choppppaaaaaaahhhh!"
