---
# this MUST be run as root, so that it can create the non priviledged user.

- name: Setup Dylans Workstation
  hosts: all
  tasks:
# update the mirrors list
    - name: download pacman mirror list
      get_url:
        url: "https://www.archlinux.org/mirrorlist/?country=US&country=GB&protocol=http&ip_version=4&use_mirror_status=on"
        dest: "/etc/pacman.d/mirrorlist"

    - name: "uncomment `#Server` in pacman mirror list"
      replace:
        dest: "/etc/pacman.d/mirrorlist"
        regexp: '^#Server'
        replace: 'Server'

    - name: "uncomment colors"
      lineinfile:
        dest: /etc/pacman.conf
        state: "present"
        regexp: "^Color"
        insertafter: "^#Color"
        line: "Color"

# install a bunch of stuff
    - name: install a bunch of stuff
      package:
        name: "{{ item }}"
        state: present
      with_items:
# basic stuff
        - breeze-gtk
        - dolphin
        - git
        - ipcalc
        - konsole
        - kde-gtk-config
        - nvidia
        - nvidia-settings
        - nvidia-utils
        - plasma
        - pwgen
        - rdesktop
        - sddm
        - sudo
        - vim
        - xorg
        - xorg-xinit
# fakeroot is needed for makepkg which is needed to install google-chrome.
        - fakeroot
# extra things that arent required for a "functioning" system
        - kcalc
        - syncthing
# THERES more STUFF TO DO FOR SETTING UP BLUETOOTH. check the archlinux bluetooth page for details
        - bluez
        - bluez-utils
# Allow members of wheel to privilege escalate without a password
    - name: allow wheel passwordless sudo privs.
      replace:
        dest: "/etc/sudoers"
        regexp: "^# %wheel ALL=\\(ALL\\) NOPASSWD"
        replace: "%wheel ALL=(ALL) NOPASSWD"
## create my non privileged user
    - name: create user
      user:
        name: dylanh
        shell: /bin/bash
# lp group allows bluetooth access, wheel allows root access to things
        groups: wheel,dylanh,lp
        home: /home/dylanh
#
 
## configuration
    - name: get an xorg configuration using nvidia-xconfig
      command: /usr/bin/nvidia-xconfig
      args:
        creates: /etc/X11/xorg.conf

# this means we can use the nvidia-settings kde app to configure the displays, and save the configuration
# in the app without it complaining about permissions.
 
    - name: make the xorg configuration editable by uses in the wheel group (me)
      file:
        path: /etc/X11
        group: wheel
        mode: '0775'

    - name: make the file created by nvidia-xconfig writable by wheel
      file:
        path: /etc/X11/xorg.conf
        group: wheel
        mode: '0775'

    - name: xinitrc
      copy:
        dest: /home/dylanh/.xinitrc
        content: |
          exec startkde
        owner: dylanh
        group: dylanh

    - name: create an sddm config drop in folder
      file: 
        path: /etc/sddm.conf.d/

    - name: create the sddm theme drop in
      copy:
        dest: /etc/sddm.conf.d/theme.conf
        content: |
          [Theme]
          Current=breeze
          CursorTheme=
          DisableAvatarsThreshold=7
          EnableAvatars=true
          FacesDir=/usr/share/sddm/faces
          ThemeDir=/usr/share/sddm/themes

# this just checks out the repo, you still need to cd to it and run makepkg -s
    - name: clone google-chrome repo
      git:
        repo: https://aur.archlinux.org/google-chrome.git
        dest: /usr/src/google-chrome
        update: no
    - name: make google-chrome source code available to me
      file: 
        path: /usr/src/google-chrome
        group: wheel
        mode: '0775'
    - name: run makepkg in the google-chrome folder we just made
      command: chdir=/usr/src/google-chrome makepkg -s --noconfirm
      args:
        creates: /usr/src/google-chrome/google-chrome-*.pkg.tar.xz
# now to install it, provided it not installed.
    - name: now install the package we just makepkg'd. I hope we can install using wildcards.
      command: chdir=/usr/src/google-chrome pacman -U --noconfirm google_chrome-*.pkg.tar.xz
      args:
        creates: /usr/bin/google-chrome-stable

# bash configuration
    - name: install bash_profile
      copy:
        dest: /home/dylanh/.bash_profile
        mode: '0644'
        content: |
          if [ -f ~/.bashrc ]; then
          	. ~/.bashrc
          fi

    - name: install bashrc
      copy:
        dest: /home/dylanh/.bashrc
        src: files/bash/bashrc
        owner: dylanh
        mode: '0644'
    - name: install vim settings
      file:
        path: ~/.vim
        owner: dylanh
        mode: '0744'

