---
# tasks file for geosword.neovim
# install neovim
- name: install package neovim from the arch tree
  pacman:
    name: "{{ item }}"
    state: present
    update_cache: true
  become: true
  with_items:
    - neovim

- name: create some folders for adding configuration / plugins
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ userdir }}/.config/nvim/"
    - "{{ userdir }}/.local/share/nvim/site/autoload/"

# Yes, I could just rsync the whole directory, without specifying the files, but I think this makes it
# more .... exact. This way there is no way you can just add a file to the directory, you have to mean it
# by adding it to code
- name: install neovim config
  synchronize:
    src: "files/{{ item }}"
    dest: "{{ userdir }}/.config/nvim/"
  with_items:
    - airline.vim
    - ale.vim
    - deoplete.vim
    - ftdetect
    - init.vim
    - plugins.vim
    - yamllint.conf

- name: run the Plugin install process in neovim
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ userdir }}/.local/share/nvim/site/autoload/"

# If you have anything like this that will report "changed" on a second run, then idempotence tests will fail. "changed_when: false" prevents this
- name: install plugins and then quit
  shell:
    cmd: "nvim +PlugInstall +qall"
  tags:
    - molecule-idempotence-notest
