# decolour ipcalc, its too hard to read
alias ipcalc="ipcalc -n"
alias sr="sudo -i"
alias sshh="ssh -Y dylanh@hoff.brad.office.comodo.net"
alias reboot="sudo reboot"
alias rdesktop='rdesktop -k en-gb -g 1152x864 -r clipboard:PRIMARYCLIPBOARD -r disk:dylans=/home/dylan/temp/'
alias findhost="~/tools/findhost.pl"
alias fssh="ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o BatchMode=yes -o ConnectTimeout=3 -o ConnectionAttempts=1"
alias mount="sudo mount"
alias umount="sudo umount"
alias passook="pwgen -s"
alias k="kubectl"
alias tms="~/tools/tmuxsplit/tmuxsplit.sh"

# make command history usefull
export HISTTIMEFORMAT="%d/%m/%y %T "
export AWS_CREDENTIAL_FILE=~/.aws/credentials
export AWS_CONFIG_FILE=~/.aws/config

# make tmux pretty
export TERM=xterm-256color
eval $(keychain --eval id_rsa id_rsa_dylans)
