---

- name: Verify
  hosts: all
  tasks:

  - name: include default variables
    include_vars:
      file: ../../defaults/main.yml

  - name: Get installed packages
    shell:
      cmd: "pacman -Q | awk '{print $1}'"
    register: installedpackages

  - name: Check packages are installed
    assert:
      that: "'{{ item }}' in {{ installedpackages.stdout.splitlines() }}"
      msg: "Package {{ item }} is not installed"
    with_items:
      - "neovim"

# just a note on the below. If we were to add a new file to this configuration, then the process would be to edit
# this unit test FIRST, run the test and see that it fails, then adjust the code to add the file, and check that it passes
  - name: stat configs so we can check they have been copied
    stat:
      path: "{{ userdir }}/.config/nvim/"
    register: filecopycheck
    with_items:
      - airline.vim
      - ale.vim
      - deoplete.vim
      - ftdetect
      - init.vim
      - plugins.vim
      - yamllint.conf

  - name: Check configs have been copied
    assert:
      that: "{{ item.stat.exists }}"
      msg: "{{ item.invocation.module_args.path }} is not present"
    with_items:
      - "{{ filecopycheck.results }}"
