# Things to run when arch is a virtualbox guest

    - name: remove virtualbox-guest-utils-nox (no xorg support) (Virtualbox only)
      package:
        name: virtualbox-guest-utils-nox
        state: absent
      register: removenox

    - name: install virtuabox-guest-utils  (Virtualbox only)
      package:
        name: virtualbox-guest-utils
        state: present

    - name: reboot if we had to remove guest-utils-nox and wait for it to come backup  (Virtualbox only)
      reboot:
      when:
        - removenox.changed

    - name: modprobe the vboxvideo drivers (Virtualbox only)
      modprobe:
        name: vboxvideo

    - name: Set the X11 config file to something simple and default  (Virtualbox only)
      shell: "/usr/bin/Xorg :0 -configure"
      args:
        creates: /root/xorg.conf.new

    - name: copy the vanilla xorg.conf to the right place
      copy:
        src: /root/xorg.conf.new
        dest: /etc/X11/xorg.conf
        remote_src: true

    - name: Hide vagrant user in sddm
      copy:
        dest: /etc/sddm.conf.d/hidevagrantuser.conf
        content: |
          [Users]
          HideUsers=vagrant
          Session=plasma.dekstop
          User=dylanh
          MinimumUid=1001
